# Generated by Django 2.1.7 on 2019-03-21 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('Description', models.TextField()),
                ('Position', models.IntegerField()),
                ('Expected_Finish', models.DateField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='DateRange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Begin_Time', models.TimeField()),
                ('End_Time', models.TimeField()),
                ('Card_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dateranges', to='timelapsed.Card')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('Name', models.TextField(max_length=100)),
                ('Position', models.IntegerField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='timelapsed.Users'),
        ),
        migrations.AddField(
            model_name='event',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='timelapsed.Users'),
        ),
        migrations.AddField(
            model_name='daterange',
            name='Event_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dateranges', to='timelapsed.Event'),
        ),
        migrations.AddField(
            model_name='daterange',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dateranges', to='timelapsed.Users'),
        ),
        migrations.AddField(
            model_name='card',
            name='Topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='timelapsed.Topic'),
        ),
        migrations.AddField(
            model_name='card',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='timelapsed.Users'),
        ),
    ]
