# Generated by Django 2.1.7 on 2019-03-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelapsed', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DateRange',
            new_name='Date_Range',
        ),
    ]
