# Generated by Django 2.1.7 on 2019-03-27 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelapsed', '0002_auto_20190321_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='User',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='date_range',
            old_name='User',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='User',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='User',
            new_name='Email',
        ),
    ]
