# Generated by Django 2.1.7 on 2019-04-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelapsed', '0004_auto_20190403_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='date_range',
            name='Day',
            field=models.TextField(default='Sunday', max_length=100),
        ),
    ]
