# Generated by Django 2.1.7 on 2019-04-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelapsed', '0005_date_range_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Expected_Finish',
        ),
    ]
