# Generated by Django 2.1.7 on 2019-04-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelapsed', '0006_remove_card_expected_finish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date_range',
            name='Begin_Date',
        ),
        migrations.RemoveField(
            model_name='date_range',
            name='End_Date',
        ),
        migrations.AddField(
            model_name='date_range',
            name='Num_Weeks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='date_range',
            name='Weeks_Skipped',
            field=models.IntegerField(default=0),
        ),
    ]
