# Generated by Django 2.2.2 on 2019-06-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelapsed', '0009_auto_20190524_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_range',
            name='Begin_Date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='date_range',
            name='Day',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='date_range',
            name='Num_Weeks',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='date_range',
            name='Weeks_Skipped',
            field=models.IntegerField(default=None),
        ),
    ]
