# Generated by Django 2.2.2 on 2019-06-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelapsed', '0012_auto_20190611_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_range',
            name='Num_Weeks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='date_range',
            name='Weeks_Skipped',
            field=models.IntegerField(default=0),
        ),
    ]
