# Generated by Django 2.2.2 on 2019-07-02 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelapsed', '0013_auto_20190611_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Relationship_Child_Action',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Type', models.TextField()),
                ('Child_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_child_id', to='timelapsed.Card')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Card_Relationship_Delete_Action',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Card_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_delete_id', to='timelapsed.Card')),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_delete_email', to='timelapsed.Users')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Card_Relationship_In_Same_Action',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Card_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_same_first_id', to='timelapsed.Card')),
                ('Child_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_same_second_id', to='timelapsed.Card')),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_same_email', to='timelapsed.Users')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Card_Relationship_Move_Action',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Card_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_move_id', to='timelapsed.Card')),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_move_email', to='timelapsed.Users')),
                ('Topic_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_topic_id', to='timelapsed.Topic')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Card_Relationship_Parent_Action',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Delete_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_parent_delete_id', to='timelapsed.Card_Relationship_Delete_Action')),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_parent_email', to='timelapsed.Users')),
                ('Move_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_parent_move_id', to='timelapsed.Card_Relationship_Move_Action')),
                ('Parent_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationships_parent_id', to='timelapsed.Card')),
                ('Same_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_parent_same_id', to='timelapsed.Card_Relationship_In_Same_Action')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Card_Relationship_Subclass_Action',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Card_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_subclass_card_id', to='timelapsed.Card')),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_subclass_email', to='timelapsed.Users')),
                ('Subclass_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_subclass_id', to='timelapsed.Subclass')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.DeleteModel(
            name='Card_Relationships',
        ),
        migrations.AddField(
            model_name='card_relationship_parent_action',
            name='Subclass_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_child_parent_id', to='timelapsed.Card_Relationship_Subclass_Action'),
        ),
        migrations.AddField(
            model_name='card_relationship_child_action',
            name='Delete_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_child_delete_id', to='timelapsed.Card_Relationship_Delete_Action'),
        ),
        migrations.AddField(
            model_name='card_relationship_child_action',
            name='Email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_child_email', to='timelapsed.Users'),
        ),
        migrations.AddField(
            model_name='card_relationship_child_action',
            name='Move_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_child_move_id', to='timelapsed.Card_Relationship_Move_Action'),
        ),
        migrations.AddField(
            model_name='card_relationship_child_action',
            name='Same_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_child_same_id', to='timelapsed.Card_Relationship_In_Same_Action'),
        ),
        migrations.AddField(
            model_name='card_relationship_child_action',
            name='Subclass_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_child_subclass_id', to='timelapsed.Card_Relationship_Subclass_Action'),
        ),
    ]
