# Generated by Django 2.2.2 on 2019-07-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelapsed', '0014_auto_20190702_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_relationship_child_action',
            name='Type',
        ),
        migrations.AddField(
            model_name='card_relationship_child_action',
            name='Parent_Action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_relationship_id', to='timelapsed.Card_Relationship_Parent_Action'),
        ),
    ]
