# Generated by Django 2.2.3 on 2019-07-26 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelapsed', '0015_auto_20190709_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_relationship_child_action',
            name='Child_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_child_id', to='timelapsed.Card'),
        ),
        migrations.AlterField(
            model_name='card_relationship_child_action',
            name='Delete_ID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_child_delete_id', to='timelapsed.Card_Relationship_Delete_Action'),
        ),
        migrations.AlterField(
            model_name='card_relationship_child_action',
            name='Move_ID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_child_move_id', to='timelapsed.Card_Relationship_Move_Action'),
        ),
        migrations.AlterField(
            model_name='card_relationship_child_action',
            name='Parent_Action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_relationship_id', to='timelapsed.Card_Relationship_Parent_Action'),
        ),
        migrations.AlterField(
            model_name='card_relationship_child_action',
            name='Same_ID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_child_same_id', to='timelapsed.Card_Relationship_In_Same_Action'),
        ),
        migrations.AlterField(
            model_name='card_relationship_child_action',
            name='Subclass_ID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_child_subclass_id', to='timelapsed.Card_Relationship_Subclass_Action'),
        ),
        migrations.AlterField(
            model_name='card_relationship_delete_action',
            name='Card_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_delete_id', to='timelapsed.Card'),
        ),
        migrations.AlterField(
            model_name='card_relationship_in_same_action',
            name='Card_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_same_first_id', to='timelapsed.Card'),
        ),
        migrations.AlterField(
            model_name='card_relationship_in_same_action',
            name='Child_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_same_second_id', to='timelapsed.Card'),
        ),
        migrations.AlterField(
            model_name='card_relationship_move_action',
            name='Card_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_move_id', to='timelapsed.Card'),
        ),
        migrations.AlterField(
            model_name='card_relationship_move_action',
            name='Topic_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_topic_id', to='timelapsed.Topic'),
        ),
        migrations.AlterField(
            model_name='card_relationship_parent_action',
            name='Delete_ID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_parent_delete_id', to='timelapsed.Card_Relationship_Delete_Action'),
        ),
        migrations.AlterField(
            model_name='card_relationship_parent_action',
            name='Move_ID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_parent_move_id', to='timelapsed.Card_Relationship_Move_Action'),
        ),
        migrations.AlterField(
            model_name='card_relationship_parent_action',
            name='Parent_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relationships_parent_id', to='timelapsed.Card'),
        ),
        migrations.AlterField(
            model_name='card_relationship_parent_action',
            name='Same_ID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_parent_same_id', to='timelapsed.Card_Relationship_In_Same_Action'),
        ),
        migrations.AlterField(
            model_name='card_relationship_parent_action',
            name='Subclass_ID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_child_parent_id', to='timelapsed.Card_Relationship_Subclass_Action'),
        ),
        migrations.AlterField(
            model_name='card_relationship_subclass_action',
            name='Card_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_subclass_card_id', to='timelapsed.Card'),
        ),
        migrations.AlterField(
            model_name='card_relationship_subclass_action',
            name='Subclass_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_subclass_id', to='timelapsed.Subclass'),
        ),
        migrations.AlterField(
            model_name='topic_relationships',
            name='Child_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_relationships_child', to='timelapsed.Topic'),
        ),
        migrations.AlterField(
            model_name='topic_relationships',
            name='Parent_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_relationships_parent', to='timelapsed.Topic'),
        ),
    ]
