# Generated by Django 2.2.3 on 2019-07-26 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelapsed', '0016_auto_20190726_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_relationship_child_action',
            name='Delete_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_child_delete_id', to='timelapsed.Card_Relationship_Delete_Action'),
        ),
        migrations.AlterField(
            model_name='card_relationship_child_action',
            name='Move_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_child_move_id', to='timelapsed.Card_Relationship_Move_Action'),
        ),
        migrations.AlterField(
            model_name='card_relationship_child_action',
            name='Same_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_child_same_id', to='timelapsed.Card_Relationship_In_Same_Action'),
        ),
        migrations.AlterField(
            model_name='card_relationship_child_action',
            name='Subclass_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_child_subclass_id', to='timelapsed.Card_Relationship_Subclass_Action'),
        ),
        migrations.AlterField(
            model_name='card_relationship_parent_action',
            name='Delete_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_parent_delete_id', to='timelapsed.Card_Relationship_Delete_Action'),
        ),
        migrations.AlterField(
            model_name='card_relationship_parent_action',
            name='Move_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_parent_move_id', to='timelapsed.Card_Relationship_Move_Action'),
        ),
        migrations.AlterField(
            model_name='card_relationship_parent_action',
            name='Same_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_parent_same_id', to='timelapsed.Card_Relationship_In_Same_Action'),
        ),
        migrations.AlterField(
            model_name='card_relationship_parent_action',
            name='Subclass_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_relationship_child_parent_id', to='timelapsed.Card_Relationship_Subclass_Action'),
        ),
    ]
